version: '3'
services:
  dolphjs-blog:
    image: # dolphjs network image id from cloud repo
    ports:
      - 8081: 8081
  mongodb:
    image: mongo:latest
    ports:
      - 6000:6000
    volumes:
      - mongo-database: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 5555: 5555
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  redis:
    image: redis
    ports:
      -6379: 6379
volumes:
  mongo-database:
    driver: local
